name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitignore"

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow runs delete
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 3

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set variables
        run: |
          git remote add upstream https://github.com/MetaCubeX/metacubexd.git
          git fetch upstream main
          echo "COMMIT=$(git rev-parse --short upstream/main)" >> $GITHUB_ENV
        shell: bash

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: latest

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm build

      - name: Publish
        run: |
          cd dist || exit 1
          git init --initial-branch=gh-pages
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "${COMMIT}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin gh-pages
